name: 'Continuous Integration'

on:
  push:
  pull_request:
  schedule:
  # Execute a weekly build on Monday at 2AM UTC
  - cron:  '0 2 * * 1'

jobs:
  # ==============
  # PYTHON PACKAGE
  # ==============

  python:
    name: Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7']

    steps:
      - uses: actions/checkout@master

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Dependencies
        run: pip install Pygments

      - name: Install
        run: pip install .

      - name: Test
        run: devenv -G -f .ci/devenv.yml -o output.yml

      - name: Check
        run: pygmentize -g output.yml

  # =============
  # DOCKER IMAGES
  # =============

  docker:
    name: 'Docker: devenv:${{ matrix.target }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - latest
          - intel
          - nvidia

    steps:
      - uses: actions/checkout@master

      - name: Build
        run: cd docker && make ${{ matrix.target }}

      - name: Login
        if: |
          github.repository == 'diegoferigo/devenv' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/master'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin

      - name: Push
        if: |
          github.repository == 'diegoferigo/devenv' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/master'
        run: "docker push diegoferigo/devenv:${{ matrix.target }}"